version: '3'

services:

  book-api:
    image: jamesaudretsch/webapp_book-api
    ports:
      - 5001:5000
    depends_on:
      - book-database
    
  front-end:
    image: jamesaudretsch/webapp_front-end
    environment:
      - BOOK_API_SERVER=http://webapp-stack_book-api:5000
    ports:
      - 5000:5000
    depends_on:
      - book-api
    
  book-database:
    image: mongo:latest
    ports:
       - 27017:27017
    